name: Test
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Build
        run: make build

      - name: Unit Tests
        run: make test

      - name: Start VyOS
        run: |
          docker run -d --privileged \
            --name vyos \
            -v ${{ github.workspace }}/.github/workflows/config.boot:/opt/vyatta/etc/config.boot.default \
            -v ${{ github.workspace }}/.github/workflows/selfsigned.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem \
            -v ${{ github.workspace }}/.github/workflows/selfsigned.key:/etc/ssl/private/ssl-cert-snakeoil.key \
            -v /lib/modules:/lib/modules \
            -p 443:443 \
            foltik/vyos:rolling-latest \
            /sbin/init

      - name: Wait for VyOS
        run: timeout 120 bash ${{ github.workspace }}/.github/workflows/wait-for-vyos.sh

      - name: Integration Tests
        run: make integration
